spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 1234
  data:
    mongodb:
      host: localhost
      port: 27017
      username: noti
      password: noti
      database: notification
      auto-index-creation: true
#      authentication-database: admin

rabbitmq:
  dynamic-id: ns.queue.wn.v0.${random.value}


playv:
  cookie:
    domain: dev-playv.co
    secure: true

cors:
  allowed-origins: https://investor.dev-coinvestor.co, https://investor.dev-playv.co, https://trader-admin.dev-playv.co, https://trader-terminal.dev-playv.co, https://trader-admin-local.playv.co, https://investor-local.playv.co, https://investor-local.dev-playv.co, https://trader-admin-local.dev-playv.co

